const data = {
  papadias: [
    {
      title: "İtalyan Papadias",
      composition:
        "Pizza Sousu, İtalyan Sosisi, Pepperoni, Mozzarella, Parmezan, Italyan ədviyyatları",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_4f6b29a2063afa150b3793240a97988e.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "1SfcpmSLl3ot4mc7Z-7ql",
    },
    {
      title: "Cheddar Meksika Papadias",
      composition:
        "Pizza sousu, Yaşıl Bibər, Qril Toyuğu, Mozzarella, Cheddar, Halapeno",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_5cf3c3909a3c5fa466dc6ed16c5836cc.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "cbz3BHsR1j8F7J4mmjx9a",
    },
    {
      title: "Dabl Cheddar Çizburger Papadias",
      composition:
        "1000 Ada sousu, Mal Əti, Pomidor, Mozzarella və Cheddar Pendirləri",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_978162a01eda0042ae1707bf563ac3e0.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "esxQUoV8zl2Mswz6eMwkC",
    },
    {
      title: "Nyu Orleans Papadias",
      composition:
        "Sarımsaq Sousu, Yaşıl Bibər, Qril Toyuğu, Qarğıdalı, Mozzarella",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_2bed10a8aa16b5835f6db36b505ba0fa.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "nusHPUToAxJyK5zQOLBaU",
    },
    {
      title: "Çiken Baffalo Papadias",
      composition:
        "Ranç Sousu, Qril Toyuğu, Pomidor, Mozzarella, Baffalo Sousu",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_13f62c1a64a60fbfd55cac0579f3d80e.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "Lmz36v0bmKw7moWxD9Oak",
    },
    {
      title: "Acılı Çiken Ranç Papadias",
      composition:
        "Ranç Sousu, Qril Toyuğu, Göbələk, Pomidor, Halapeno, Mozarella",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_19c1323adbcb9a595018f5979a862204.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "H3WlBKayVTVKvh-EhVUIO",
    },
    {
      title: "Çiken BBQ Papadias",
      composition: "Qril Toyuğu, Göbələk, Mozzarella, Barbekyu sousu",
      img: "https://order.papajohns.az/images/menu/PJ%20Azerbaijan/336x224_f7db43402b2cd4bda0a88b5028bc1dfd.jpg",
      price: "9",
      category: "papadias",
      variations: [],
      id: "JNHsV9QGKzfZOnuqxOV85",
    },
  ],

  qalyanaltilar: [
    {
      img: "https://www.papajohns.az/uploads/images/pepperoni_rolls.jpg",
      title: "Pepperoni Rolls",
      composition: "8 ədəd roll, Pizza-Sous",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "FZv6qE3czddyXcsPNugrG",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/Cheddar-Rolls.png",
      title: "Cheddar Rolls ",
      composition: "8 ədəd roll, Pizza-Sous",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "8VV_biUJlxgO0O2IffnHJ",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/Chicken-Rolls.jpg",
      title: "Çiken Rolls",
      composition: "Qril Toyuğu, Turşu Xiyar, Mozzarella Pendiri, Ranç Sousu",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "O7J-mgCfR2ozRkdqNTU5C",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/Spicy-Chicken-Rolls.jpg",
      title: "Acılı Çiken Rolls",
      composition:
        "Qril Toyuğu, Halapeno Bibəri, Mozzarella Pendiri, Ranç Sousu",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "6XN5XJiPROXkak5EU0cjg",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/Cheddar-Pendirli-%C3%A7ubuqlar.png",
      title: "Cheddar Pendirli Çubuqlar",
      composition: "1 ədəd Pizza sousu, 1 ədəd sarımsaq sousu",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "fsH2cBcOmsHUW3xC3VyMb",
    },
    {
      img: "https://www.papajohns.az/uploads/images/pendirli_cubuqlar.jpg",
      title: "Pendirli Çubuqlar",
      composition: " Sarımsaq Sousu, Pizza-Sous",
      price: "7",
      category: "qalyanaltilar",
      variations: [],
      id: "tAdon4jRY33T7ZLIi0sT5",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/pendirli-chubuqlar-bikon%20(1).png",
      title: "Vetçina və Göbələkli Çubuqlar",
      composition: "Sarımsaq Sousu, Vetçina, Göbələk, Mozzarella",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "NMSCI_Jks9Uw9n0ASSggu",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/pendirli-chubuqlar-kuncut%20(1).png",
      title: "Küncütlü Pendirli Çubuqlar",
      composition: "Sarımsaq Sousu, Mozzarella, Küncüt",
      price: "8",
      category: "qalyanaltilar",
      variations: [],
      id: "LmUbRtShRGFV4sWl0rIJx",
    },
    {
      img: "https://www.papajohns.az/uploads/images/sarimsaqli_cubuqlar.jpg",
      title: "Sarımsaqlı Çubuqlar",
      composition: "Sarımsaq Sousu, Pizza-Sous",
      price: "3",
      category: "qalyanaltilar",
      variations: [],
      id: "g-T5qOh1aGE8vhVfdcrMK",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Campaigns/2023/Noyabr/New%20products/Chiken-Poppers-BBQ-320x220.png",
      title: "Çiken Poppers BBQ ",
      composition: "150 qram",
      price: "6",
      category: "qalyanaltilar",
      variations: [],
      id: "am5-K4n64G7BegMvwWZoT",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Calzone_Chicken.jpg",
      title: "Kalzone, Qril Toyuğu və Göbələk",
      composition: "Qril Toyuğu, Göbələk, Sarımsaq Sousu, Mozzarella ",
      price: "6",
      category: "qalyanaltilar",
      variations: [],
      id: "yYqpNE4R6TUOV6MsLGJGW",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Calzone_Pepperoni.jpg",
      title: "Kalzone, Pepperoni və İtalyan Sosisi",
      composition: "Pepperoni, İtalyan Sosisləri, Sarımsaq Sousu, Mozzarella ",
      price: "6",
      category: "qalyanaltilar",
      variations: [],
      id: "2Zx4jxh4QrW0bgGRcjpzl",
    },
    {
      img: "https://www.papajohns.az/uploads/images/snacks/pendirli-m%C3%BCt%C9%99kk%C9%99l%C9%99r.png",
      title: "Pendirli mütəkkələr",
      composition: "1 ədəd Pizza sousu, 1 ədəd Sarımsaq sousu",
      price: "10",
      category: "qalyanaltilar",
      variations: [],
      id: "kdgUp2zTgsmbNOpQYf4yP",
    },
    {
      img: "https://www.papajohns.az/uploads/images/toyuq_qanadlari.jpg",
      title: "Toyuq Qanadları",
      composition: "Barbekyu və ya Baffalo sousu ilə (250 gr)",
      price: "9",
      category: "qalyanaltilar",
      variations: [],
      id: "9iyX49FajRbm4ARaQYvXA",
    },
    {
      img: "https://www.papajohns.az/uploads/images/kartof_dilimleri.jpg",
      title: "Kartof Dilimləri",
      composition: "200 qram",
      price: "4.9",
      category: "qalyanaltilar",
      variations: [],
      id: "4KFYnIxCe1n5CTPvEzM-G",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Campaigns/2024/%C3%87iken%20Poppers.jpg",
      title: "Çiken Poppersləri",
      composition: "150 qram",
      price: "6",
      category: "qalyanaltilar",
      variations: [],
      id: "FyzDz2x93NuoLfDz8xzKJ",
    },
  ],
  salat: [
    {
      img: "https://www.papajohns.az/uploads/images/Caesar%20Salad.jpg",
      title: "Sezar Salatı",
      composition:
        "Qril Toyuq, Aysberq Kahı, Suxari, Pomidor, Parmesan, Sezar Sousu",
      price: "9",
      category: "salat",
      variations: [],
      id: "dnRddjSK2MyvNe5h20rNB",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Greek%20Salad.jpg",
      title: "Yunan Salatı",
      composition:
        "Xiyar, Pomidor, Aysberq Kahı, Qara Zeytun, Feta Pendiri, İtalyan Sousu, Oreqano, Yaşıl Bibər",
      price: "6",
      category: "salat",
      variations: [],
      id: "0jf9vuFBlBIoG2jjSBUn2",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Garden%20Slad.jpg",
      title: "Tərəvəz Salatı",
      composition:
        "Xiyar, Pomidor, Aysberq Kahı, Qara Zeytun, Yaşıl Bibər, İtalyan Sousu",
      price: "5",
      category: "salat",
      variations: [],
      id: "exL_CFztVJmGQnnUY5-Ia",
    },
    {
      img: "https://www.papajohns.az/uploads/images/salads/Tuna%20Salad_no_tomato_Azer_158_1.jpg",
      title: "Tuna Salatı",
      composition:
        "Ton Balığı, Aysberq Kahı, Qara Zeytun, Qarğıdalı, Xiyar, İtalyan Sousu",
      price: "8",
      category: "salat",
      variations: [],
      id: "PK1RYCW7elEyIqRFrABQs",
    },
  ],
  pasta: [
    {
      img: "https://www.papajohns.az/uploads/images/pasta_super_papa.jpg",
      title: "Pasta Super Papa",
      composition:
        "Spagetti, Pepperoni, Vetçina, İtalyan Sosisləri, Yaşıl Bibər, Göbələk, Pizza Sous, Mozzarella ",
      price: "9",
      category: "pasta",
      variations: [],
      id: "FHMPJoS82m0RYMQq6iB5h",
    },
    {
      img: "https://www.papajohns.az/uploads/images/pasta_chicken_ranch.jpg",
      title: "Çiken Ranç Pasta",
      composition: "Spagetti, Qril Toyuğu, Göbələk, Ranç Sousu, Mozzarella ",
      price: "9",
      category: "pasta",
      variations: [],
      id: "zZJgLH7n4Ki_81LWnM_qt",
    },
    {
      img: "https://www.papajohns.az/uploads/images/pasta_mamas_pasta.jpg",
      title: "Mama Pasta",
      composition: "Spagetti, Parmezan, Oregano, Pizza Sous, Mozzarella ",
      price: "7",
      category: "pasta",
      variations: [],
      id: "fKffI5lk0LMW6whzcHBs8",
    },
  ],
  souses: [
    {
      img: "https://www.papajohns.az/uploads/images/Ranch.jpg",
      title: "Ranç Sousu",
      composition: "",
      price: "0.8",
      category: "souses",
      variations: [],
      id: "R6iGC1C98qT7Y4EDn9A5x",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Barbeque.jpg",
      title: "Barbekyu Sousu",
      composition: "",
      price: "0.8",
      category: "souses",
      variations: [],
      id: "RfbfLtlrFUnPIZYrjkP94",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Garlic.jpg",
      title: "Sarımsaq Sousu",
      composition: "",
      price: "0.8",
      category: "souses",
      variations: [],
      id: "VJJtPIERk_JdyXCxqyWES",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Buffalo.jpg",
      title: "Baffalo Sousu",
      composition: "",
      price: "0.8",
      category: "souses",
      variations: [],
      id: "rdKpnzxGTjLMjNtq2lmnM",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Thousand-island.jpg",
      title: "1000 Ada Sousu",
      composition: "",
      price: "0.8",
      category: "souses",
      variations: [],
      id: "-yEn5O7SS7e3bjaVkcpRP",
    },
    {
      img: "https://www.papajohns.az/uploads/images/Pizza.jpg",
      title: "Pizza Sousu",
      composition: "",
      price: "0.8",
      category: "souses",
      variations: [],
      id: "XWIUvwpr7HxfPyHd1xPwx",
    },
  ],
  icki: [
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1cocacola.png",
      title: "Coca Cola 500ml",
      composition: "",
      price: "2.5",
      category: "icki",
      variations: [],
      variety: [],
      id: "mOELfoWWgVpv80bcDqjjq",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Coca-cola-shekersiz.png",
      title: "Coca-Cola Şəkərsiz 500ml",
      composition: "",
      price: "2.5",
      category: "icki",
      variations: [],
      variety: [],
      id: "-1h3P3_WohQhZal5DDEXF",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Sprite.png",
      title: "Sprite 500ml",
      composition: "",
      price: "2.5",
      category: "icki",
      variations: [],
      variety: [],
      id: "hVq6OZcH0dzGMoMqfkyve",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Cappi.png",
      title: "Meyvə Şirələri - Cappy",
      composition: "",
      price: "1.5",
      category: "icki",
      variations: [],
      variety: [
        "Portağal (200 ml) -  1.5 M",
        "Multivitamin (200 ml) -  1.5 M",
        "Albalı (200 ml) -  1.5 M",
        "Şaftalı (200 ml) -  1.5 M",
        "Alma (200 ml) -  1.5 M",
      ],
      id: "ngXXdWf0-bSFEvEzkcijK",
    },
    {
      img: "https://www.papajohns.az/uploads/images/milla.jpg",
      title: "Ayran 200ml",
      composition: "",
      price: "1.5",
      category: "icki",
      variations: [],
      variety: ["Nanəli -  1.5 M", "Adi -  1.5 M"],
      id: "wS3k04rZQ5JOlGGH_YC6Q",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Fanta.png",
      title: "Fanta 500ml",
      composition: "",
      price: "2.5",
      category: "icki",
      variations: [],
      variety: [],
      id: "wWIWoI2bPKXivuKxQFid0",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Bonaqua.png",
      title: "Qazsız Su 500ml",
      composition: "",
      price: "1",
      category: "icki",
      variations: [],
      variety: [],
      id: "pagGDP6yMZ31FSrW6hHqr",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Bonaqua.png",
      title: "Qazlı Su 500ml",
      composition: "",
      price: "1",
      category: "icki",
      variations: [],
      variety: [],
      id: "kC6EeVDTMr0K9CPRMQeIU",
    },
    {
      img: "https://www.papajohns.az/uploads/images/drinks/1Fusetea.png",
      title: "Fuse Tea, 500ml",
      composition: "",
      price: "3",
      category: "icki",
      variations: [],
      variety: ["Şaftalı -  3 M", "Limon -  3 M", "Mango Ananas -  3 M"],
      id: "IH0kTa907i600LNrOCAhW",
    },
  ],
  desertlar: [
    {
      img: "https://www.papajohns.az/uploads/images/desert/Brownie--320x220-px.png",
      title: "Brownie",
      composition: "",
      price: "7",
      category: "desertlar",
      variations: [],
      variety: [],
      id: "V5TkU5_Jb5cGfmey9bu-O",
    },
    {
      img: "https://www.papajohns.az/uploads/images/desert/Tiramisu--320x220-px.png",
      title: "Tiramisu",
      composition: "",
      price: "7",
      category: "desertlar",
      variations: [],
      variety: [],
      id: "LqUOx499IGm5KS69gzWCW",
    },
    {
      img: "https://www.papajohns.az/uploads/images/desert/%C5%9Eokoladl%C4%B1-sufle.png",
      title: "Şokoladlı Sufle ",
      composition: "",
      price: "5",
      category: "desertlar",
      variations: [],
      variety: [],
      id: "Rl_H4YpvxFumTx-sND0V5",
    },
    {
      img: "https://www.papajohns.az/uploads/images/desert/raspberry-CHEESECAKE.png",
      title: "Moruqlu Cheesecake",
      composition: "",
      price: "7",
      category: "desertlar",
      variations: [],
      variety: [],
      id: "p2GBXwJHaa1mHBRJru5uF",
    },
    {
      img: "https://www.papajohns.az/uploads/images/desert/dondurma%20algida.jpg",
      title: "Dondurma",
      composition: "",
      price: "2",
      category: "desertlar",
      variations: [],
      variety: ["Çiyələkli -  2 M", "Şokoladlı -  2 M"],
      id: "mK-6aVd-B5Ndw3DrHCvQF",
    },
  ],
  category: [
    {
      id: 222,
      category: "kampaniyalar",
      slug: "kampaniyalar",
    },
    {
      id: 1,
      category: "papadias",
      slug: "papadias",
    },
    {
      id: 2,
      category: "pizza",
      slug: "pizza",
    },
    {
      id: 3,
      category: "qalyanaltilar",
      slug: "qalyanaltilar",
    },
    {
      id: 4,
      category: "salat",
      slug: "salat",
    },
    {
      id: 5,
      category: "pasta",
      slug: "pasta",
    },
    {
      id: 6,
      category: "souses",
      slug: "souses",
    },
    {
      id: 7,
      category: "icki",
      slug: "icki",
    },
    {
      id: 8,
      category: "desertlar",
      slug: "desertlar",
    },
  ],
};

const cardsContainer = document.getElementById("cards");

data.papadias.forEach((item) => {
  const card = document.createElement("div");
  card.classList.add("card");
  card.innerHTML = `
                <img src="${item.img}" alt="${item.title}">
                <h3>${item.title}</h3>
                <p>${item.composition}</p>
                <p><strong>Qiymət:</strong> ${item.price} AZN</p>
                <button class="select-button">Bunu seç</button>
            `;
  cardsContainer.appendChild(card);
});



